version: '3.3'
services:
  potm-mysql:
    build:
      context: ./db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: potm-mysql
    image: jseckill-mysql
    ports:
      - 13306:3306
    volumes:
      - ./docker-compose-data/mysql:/var/lib/mysql

  potm-redis:
    image: redis:7.0.0
    ports:
      - 16379:6379
    restart: always
    container_name: jseckill-redis
    hostname: jseckill-redis
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./docker-compose-data/redis:/data
